-- Krostio V2: Database Initialization and Migration Script
-- Designed for Supabase (PostgreSQL with built-in Auth schemas)

-- 1. Create Profiles table (extending auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  full_name TEXT,
  avatar_url TEXT DEFAULT 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces',
  tier TEXT DEFAULT 'Free' CHECK (tier IN ('Free', 'Pro', 'Pro+')),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  phone_number TEXT,
  monthly_income_goal NUMERIC DEFAULT 5000,
  tax_filing_status TEXT DEFAULT 'Single'
);

-- Enable Row Level Security (RLS) for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any, then create cleanly
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow users to view their own profile" ON public.profiles;
    DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.profiles;
    DROP POLICY IF EXISTS "Allow profile insertion on sign up" ON public.profiles;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

CREATE POLICY "Allow users to view their own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Allow users to update their own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Allow profile insertion on sign up"
  ON public.profiles FOR INSERT
  WITH CHECK (true);


-- 2. Create Earnings table (sync'd platform records)
CREATE TABLE IF NOT EXISTS public.earnings (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  date TEXT NOT NULL, -- format: YYYY-MM (chronological monthly ledger key)
  verified_by TEXT DEFAULT 'Argyle',
  argyle_timestamp TIMESTAMPTZ DEFAULT NOW(),
  status TEXT CHECK (status IN ('Growing', 'Stable', 'Seasonal', 'Declining')),
  category TEXT CHECK (category IN ('rideshare', 'delivery', 'freelance_tech', 'freelance_creative')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for earnings
ALTER TABLE public.earnings ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow users to manage their own earnings" ON public.earnings;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

CREATE POLICY "Allow users to manage their own earnings"
  ON public.earnings FOR ALL
  USING (auth.uid() = user_id);


-- 2b. Secondary earnings_feed table for server.ts ingest compatibility
CREATE TABLE IF NOT EXISTS public.earnings_feed (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  date TEXT NOT NULL,
  verified_by TEXT DEFAULT 'Argyle',
  category TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Allow public read/write or user-specific control
ALTER TABLE public.earnings_feed ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow public write and read for general platform sync" ON public.earnings_feed;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

CREATE POLICY "Allow public write and read for general platform sync"
  ON public.earnings_feed FOR ALL
  USING (true);


-- 3. Create Platform Connections table (connected credentials)
CREATE TABLE IF NOT EXISTS public.platform_connections (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  status TEXT CHECK (status IN ('connected', 'disconnected', 'syncing')),
  last_synced TEXT NOT NULL,
  total_earnings NUMERIC DEFAULT 0,
  tenure_months INT DEFAULT 0,
  icon TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, platform)
);

-- Enable RLS for connections
ALTER TABLE public.platform_connections ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow users to manage their own connections" ON public.platform_connections;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

CREATE POLICY "Allow users to manage their own connections"
  ON public.platform_connections FOR ALL
  USING (auth.uid() = user_id);


-- 4. Create Verification Reports table
CREATE TABLE IF NOT EXISTS public.reports (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  report_name TEXT NOT NULL,
  use_case TEXT NOT NULL,
  date_range TEXT NOT NULL,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  valid_through TIMESTAMPTZ,
  include_stability_score BOOLEAN DEFAULT true,
  include_tax_match BOOLEAN DEFAULT true,
  notes TEXT,
  argyle_verification_id TEXT,
  share_token TEXT UNIQUE,
  status TEXT CHECK (status IN ('Active', 'Revoked')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for reports
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow users to manage their own reports" ON public.reports;
    DROP POLICY IF EXISTS "Allow public select of report via share token" ON public.reports;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

CREATE POLICY "Allow users to manage their own reports"
  ON public.reports FOR ALL
  USING (auth.uid() = user_id);

CREATE POLICY "Allow public select of report via share token"
  ON public.reports FOR SELECT
  USING (true);


-- 5. Create Tax Write-offs table (write_offs)
CREATE TABLE IF NOT EXISTS public.write_offs (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  category TEXT CHECK (category IN ('Mileage', 'Platform Fees', 'Internet & Phone', 'Equipment', 'Other')),
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for write_offs
ALTER TABLE public.write_offs ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow users to manage their own write_offs" ON public.write_offs;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

CREATE POLICY "Allow users to manage their own write_offs"
  ON public.write_offs FOR ALL
  USING (auth.uid() = user_id);


-- 6. Create Sync Logs table (timeline events feed)
CREATE TABLE IF NOT EXISTS public.sync_logs (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  timestamp TEXT NOT NULL,
  platform TEXT NOT NULL,
  amount NUMERIC DEFAULT 0,
  type TEXT CHECK (type IN ('earning_sync', 'connection_created', 'webhook_trigger')),
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for sync_logs
ALTER TABLE public.sync_logs ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Allow users to manage their own sync_logs" ON public.sync_logs;
EXCEPTION
    WHEN undefined_object THEN NULL;
END $$;

CREATE POLICY "Allow users to manage their own sync_logs"
  ON public.sync_logs FOR ALL
  USING (auth.uid() = user_id);


-- 7. Automated profile creation trigger when a user registers via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url, tier)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'avatar_url', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces'),
    'Free'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Clear previous trigger just in case
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
